name: rstsocial
description: Social UI Showcase
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Utils
  device_info_plus: ^9.0.3
  intl: ^0.19.0
  flutter_screenutil: ^5.8.4
  flutter_easyloading: ^3.0.5
  logger: ^2.0.1
  path_provider: ^2.0.14
  # Network
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.2.3
  http: ^1.1.0
  dio: ^5.3.2

  # Navigation & Notification
  url_launcher: ^6.1.12
  flutter_local_notifications: ^17.2.3
  open_store: ^0.5.0
  webview_flutter: ^4.2.4

  # Media (Image, Permission, Video)
  permission_handler: ^11.0.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.2
  flutter_image_compress: ^2.0.4
  video_player: ^2.7.2


  # Firebase
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  country_code_picker: ^3.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Additional UI Elements (Toast, Popup, Addition Display)
  fluttertoast: ^8.2.2
  custom_pop_up_menu: ^1.2.4
  flutter_reaction_button: ^3.0.0+2
  emoji_picker_flutter: ^1.6.3

  # Location
  geolocator: ^13.0.1

  # Other UI Elements
  azlistview: ^2.0.0
  flutter_animate: ^4.2.0+1
  timeago: ^3.6.0
  video_thumbnail: ^0.5.3

  # Amplify AWS
  amplify_flutter: ^1.6.0
  amplify_auth_cognito: ^1.6.0
  rename: ^3.0.1

  flutter_native_splash: any


#  back_button_interceptor: ^7.0.0


  # Useful pub packages_info:
  #  expandable: ^5.0.1
  #  uuid: ^3.0.7
  #  readmore: ^2.2.0
  #  path_provider: ^2.1.0
  # flutter_app_version_checker: any
  #  flutter_html: ^3.0.0-beta.2
  #   pin_code_fields: ^8.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Icon
      fonts:
        - asset: assets/fonts/icomoon.ttf

flutter_launcher_icons:
  ios: false
  android: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/images/splash_icon.png
  android: true
  ios: true
  color_dark: "#ffffff"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/images/splash_icon.png
  #branding_dark: assets/dart_dark.png
  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    image: assets/images/splash_icon.png

    # Splash screen background color.
    color: "#ffffff"

    # App icon background color.
    #icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    image_dark: assets/images/splash_icon.png
    color_dark: "#ffffff"
    #icon_background_color_dark: "#eeeeee"
  fullscreen: true
